# Generated by Django 3.0.2 on 2020-01-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Date_in',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Date dd/mm/year '),
        ),
    ]
